module.exports = {
  person: [
    {
      class: "form-check-input ",
      type: "checkbox",
      name: "first_name",
      value: "first_name",
      id: "first_name",
      classLabel: "form-check-label ",
      for: "first_name",
      content: "First Name",
    },
    {
      class: "form-check-input  ",
      type: "checkbox",
      name: "last_name",
      value: "last_name",
      id: "last_name",
      classLabel: "form-check-label  ",
      for: "last_name",
      content: "Last Name",
    },
    {
      class: "form-check-input  ",
      type: "checkbox",
      name: "full_name",
      value: "full_name",
      id: "full_name",
      classLabel: "form-check-label",
      for: "full_name",
      content: "Full Name",
    },
    {
      class: "form-check-input  ",
      type: "checkbox",
      name: "username",
      value: "username",
      id: "username",
      classLabel: "form-check-label",
      for: "username",
      content: "Username",
    },
    {
      class: "form-check-input  ",
      type: "checkbox",
      name: "email",
      value: "email",
      id: "email",
      classLabel: "form-check-label",
      for: "email",
      content: "Email",
    },
    {
      class: "form-check-input  ",
      type: "checkbox",
      name: "password",
      value: "password",
      id: "password",
      classLabel: "form-check-label",
      for: "password",
      content: "Password",
    },
    {
      class: "form-check-input  ",
      type: "checkbox",
      name: "phone",
      value: "phone",
      id: "phone",
      classLabel: "form-check-label",
      for: "phone",
      content: "Phone"
    }
  ],
  place: [
    {
      class: "form-check-input  ",
      type: "checkbox",
      name: "address",
      value: "address",
      id: "address",
      classLabel: "form-check-label",
      for: "address",
      content: "Full Street Address"
    },
    {
      class: "form-check-input  ",
      type: "checkbox",
      name: "address1",
      value: "address1",
      id: "address1",
      classLabel: "form-check-label",
      for: "address1",
      content: "Simple Street Address"
    },
    {
      class: "form-check-input  ",
      type: "checkbox",
      name: "building_number",
      value: "building_number",
      id: "building_number",
      classLabel: "form-check-label",
      for: "building_number",
      content: "Building Number"
    },
    {
      class: "form-check-input  ",
      type: "checkbox",
      name: "street",
      value: "street",
      id: "street",
      classLabel: "form-check-label",
      for: "street",
      content: "Street"
    },
    {
      class: "form-check-input ",
      type: "checkbox",
      name: "city",
      value: "city",
      id: "city",
      classLabel: "form-check-label ",
      for: "city",
      content: "City",
    },
    {
      class: "form-check-input ",
      type: "checkbox",
      name: "state",
      value: "state",
      id: "state",
      classLabel: "form-check-label ",
      for: "state",
      content: "State",
    },
    {
      class: "form-check-input  ",
      type: "checkbox",
      name: "state_abbr",
      value: "state_abbr",
      id: "state_abbr",
      classLabel: "form-check-label",
      for: "state_abbr",
      content: "State Abbrev."
    }
  ],
  thing: [
    {
      class: "form-check-input ",
      type: "checkbox",
      name: "safe_color_name",
      value: "safe_color_name",
      id: "safe_color_name",
      classLabel: "form-check-label ",
      for: "safe_color_name",
      content: " safe color name",
    },
    {
      class: "form-check-input ",
      type: "checkbox",
      name: "string",
      value: "string",
      id: "string",
      classLabel: "form-check-label ",
      for: "string",
      content: "String",
    },
    {
      class: "form-check-input ",
      type: "checkbox",
      name: "coin_flip ",
      value: "coin_flip ",
      id: "coin_flip",
      classLabel: "form-check-label ",
      for: "coin_flip ",
      content: "Coin flip (heads = true)",
    },
    {
      class: "form-check-input ",
      type: "checkbox",
      name: "month_name",
      value: "month_name",
      id: "month_name",
      classLabel: "form-check-label ",
      for: "month_name",
      content: "Name of Month",
    },
    {
      class: "form-check-input ",
      type: "checkbox",
      name: "year",
      value: "year",
      id: "year",
      classLabel: "form-check-label",
      for: "year",
      content: "Year",
    },
    {
      class: "form-check-input ",
      type: "checkbox",
      name: "card_type",
      value: "card_type",
      id: "card_type",
      classLabel: "form-check-label ",
      for: "card_type",
      content: "Credit Card Type",
    },
    {
      class: "form-check-input ",
      type: "checkbox",
      name: "card_number",
      value: "card_number",
      id: "card_number",
      classLabel: "form-check-label ",
      for: "card_number",
      content: "Credit Card Number",
    }
    
  ],
};
